services:

  db:
    image: mariadb
    # restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: grupo7
    volumes:
      - ./mysq_db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1